alter table public.accumulator_state     enable row level security;
alter table public.accumulator_switches  enable row level security;
alter table public.bnb_live_positions    enable row level security;
alter table public.bnb_live_runs         enable row level security;
alter table public.bnb_live_settings     enable row level security;
alter table public.bot_runs              enable row level security;
alter table public.faking_positions      enable row level security;
alter table public.faking_runs           enable row level security;
alter table public.faking_settings       enable row level security;
alter table public.live_positions        enable row level security;
alter table public.live_runs             enable row level security;
alter table public.live_settings         enable row level security;
alter table public.positions             enable row level security;
alter table public.xlm_live_positions    enable row level security;
alter table public.xlm_live_runs         enable row level security;
alter table public.xlm_live_settings     enable row level security;
alter table public.xrp_live_positions    enable row level security;
alter table public.xrp_live_runs         enable row level security;
alter table public.xrp_live_settings     enable row level security;

create policy "anon_read" on public.accumulator_state     for select to anon using (true);
create policy "anon_read" on public.accumulator_switches  for select to anon using (true);
create policy "anon_read" on public.bnb_live_positions    for select to anon using (true);
create policy "anon_read" on public.bnb_live_runs         for select to anon using (true);
create policy "anon_read" on public.bnb_live_settings     for select to anon using (true);
create policy "anon_read" on public.bot_runs              for select to anon using (true);
create policy "anon_read" on public.faking_positions      for select to anon using (true);
create policy "anon_read" on public.faking_runs           for select to anon using (true);
create policy "anon_read" on public.faking_settings       for select to anon using (true);
create policy "anon_read" on public.live_positions        for select to anon using (true);
create policy "anon_read" on public.live_runs             for select to anon using (true);
create policy "anon_read" on public.live_settings         for select to anon using (true);
create policy "anon_read" on public.positions             for select to anon using (true);
create policy "anon_read" on public.xlm_live_positions    for select to anon using (true);
create policy "anon_read" on public.xlm_live_runs         for select to anon using (true);
create policy "anon_read" on public.xlm_live_settings     for select to anon using (true);
create policy "anon_read" on public.xrp_live_positions    for select to anon using (true);
create policy "anon_read" on public.xrp_live_runs         for select to anon using (true);
create policy "anon_read" on public.xrp_live_settings     for select to anon using (true);
