-- Unified market-data table (2026-09-28, direct request): replaces the two separate
-- lighter_btc_price_ticks / lighter_btc_trade_flow tables for Worker 3 only -- one table, one
-- logger (run_market_data_logger_forever), full order-book depth (not just best bid/ask) plus
-- executed trade prints, so a future fast-reacting bot has one simple place to read a complete
-- market-data stream from.
--
-- Two row "kind"s share the table:
--   'book'  -- bids/asks are the FULL order book at that moment (jsonb array of {price, size}
--             per level), best_bid/best_ask are denormalized copies of the top level for fast
--             top-of-book queries without unpacking the arrays.
--   'trade' -- an executed trade print: price, size, usd_amount, is_maker_ask (true = the
--             resting order was an ask, i.e. the taker/aggressor bought).

create table if not exists lighter_stoch_dca_btc_market_data (
  id bigint generated by default as identity primary key,
  ts timestamptz not null default now(),
  kind text not null check (kind in ('book', 'trade')),
  bids jsonb,
  asks jsonb,
  best_bid double precision,
  best_ask double precision,
  trade_id bigint,
  price double precision,
  size double precision,
  usd_amount double precision,
  is_maker_ask boolean,
  source text not null
);

create unique index if not exists lighter_stoch_dca_btc_market_data_trade_id_uniq
  on lighter_stoch_dca_btc_market_data (trade_id) where trade_id is not null;
create index if not exists lighter_stoch_dca_btc_market_data_ts_idx
  on lighter_stoch_dca_btc_market_data (ts);
create index if not exists lighter_stoch_dca_btc_market_data_kind_ts_idx
  on lighter_stoch_dca_btc_market_data (kind, ts);

alter publication supabase_realtime add table lighter_stoch_dca_btc_market_data;
alter table lighter_stoch_dca_btc_market_data enable row level security;
create policy "anon read" on lighter_stoch_dca_btc_market_data for select using (true);
